# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 806d9e10b5d79fb43132c3dcaf02a2b12cf2aa58f21ac95bcda7a2c4ebe3e10c915b69b4d124695d21f83114a6e19a5d22bd3aaeb661db6f39e64c6985b1e752

test:
  secret_key_base: a09c94bcc741199c081937afff6ede6645bd67506cde1f583dc9cc1da3bb0d5ef01e3734117cfa3b29fbd647ad8572554e91f73dbfd74876ddf14e2e8e4a9865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
